server:
  port: 8101
spring:
  application:
    name: office-monitor
#  security: # 配置登录用户名和密码
#    user:
#      name: simplefanc
#      password: 123456
  boot:  # 不显示office-monitor的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}

  profiles:
    active: dev