server:
  port: 8084
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 抽样率默认是0.1（10% 丢弃90%数据）
      # 为了测试方便设为1.0
      probability: 1.0
  activiti:
    database-schema-update: true
    #    对于历史数据，保存到何种粒度
    historyLevel: audit
    #    使用历史表
    db-history-used: true
  quartz:
    job-store-type: jdbc

feign:
  httpclient:
    # 让feign使用apache httpclient做请求，而不是默认的urlclient
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
  client:
    config:
      # 全局配置
      default:
        requestInterceptors:
          - com.simplefanc.office.common.interceptor.TokenRelayRequestInterceptor

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.simplefanc.office.meeting.entity
  configuration:
#    控制台可以打印SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always