server:
  port: 8085
spring:
  cloud:
    gateway:
      discovery:
        # 让spring cloud gateway从nacos上获取微服务
        locator:
          enabled: true

# actuator配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always